name: wildfire-detection
channels:
  - conda-forge
dependencies:
  - python=3.9.16
  - rioxarray
  - jupyter
  - xarray
  - pandas
  - geopandas
  - numpy
  - joblib
  - shapely
  - matplotlib
  - contextily
  - geoviews
  - holoviews
  - bokeh
  - folium
  - dask
